### PR TITLE
Add option to filter HoC by author (Git)

### PR DESCRIPTION
**Pull request by Duneus**
Hello!

I've taken the opportunity to contribute to this project by implementing a feature proposed in #18. 
This is my first ever contribution in Ruby, so I'd appreciate feedback, even though this is a very small change.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#19](https://github.com/yegor256/hoc/issues/19) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@Duneus looks good to me, let's try to merge

**Comment by 0crat** [comment]
Job `gh:yegor256/hoc#19` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#19](https://github.com/yegor256/hoc/issues/19) is now out of scope

**Pull request merged**
